# Generated by Django 2.2.3 on 2019-07-11 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='evaluation',
            field=models.ManyToManyField(related_name='evaluation', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='subuser',
            name='parent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dislike',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='sub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='accounts.SubUser'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
