# Generated by Django 2.2.3 on 2019-07-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='dislike',
        ),
    ]
