# Generated by Django 2.2.3 on 2019-07-16 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190714_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='logined',
        ),
        migrations.AlterField(
            model_name='likedislikemarked',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='likedislikemarked',
            name='sub_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='accounts.SubUser'),
        ),
    ]
