# Generated by Django 2.2.3 on 2019-07-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190705_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='logined',
            field=models.BooleanField(default=False),
        ),
    ]
