# Generated by Django 2.2.3 on 2019-07-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0003_auto_20190711_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDisLikeMarked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.SmallIntegerField(default=0)),
                ('marked', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='movies.Movie')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='accounts.SubUser')),
            ],
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
    ]
