# Generated by Django 2.2.3 on 2019-07-17 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190716_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedislikemarked',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likedislikemarked',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
