# Generated by Django 2.2.3 on 2019-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190721_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='profile_image_path',
            field=models.TextField(blank=True),
        ),
    ]
