# Generated by Django 2.2.3 on 2019-07-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
