# Generated by Django 2.2.3 on 2019-07-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190711_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='subuser',
            name='like',
        ),
        migrations.AlterField(
            model_name='subuser',
            name='kid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='subuser',
            name='logined',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
