# Generated by Django 2.2.3 on 2019-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190717_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
