# Generated by Django 2.2.3 on 2019-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190724_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='image_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
