# Generated by Django 2.2.3 on 2019-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190724_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subuser',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
