# Generated by Django 2.2.3 on 2019-07-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190725_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='profileimage',
            name='f_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_images', to='accounts.ProfileImageCategory'),
        ),
    ]
