# Generated by Django 2.2.3 on 2019-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190726_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislikemarked',
            name='like_or_dislike',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='likedislikemarked',
            name='marked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
