# Generated by Django 2.2.3 on 2019-08-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190805_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislikemarked',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
