# Generated by Django 2.2.3 on 2019-07-19 04:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/movie/<django.db.models.fields.CharField>/video')),
                ('sample_video_file', models.FileField(blank=True, null=True, upload_to='media/movie/<django.db.models.fields.CharField>/sample_video')),
                ('production_date', models.CharField(blank=True, max_length=10)),
                ('uploaded_date', models.DateField(default=django.utils.timezone.now)),
                ('synopsis', models.TextField(blank=True)),
                ('running_time', models.CharField(max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('logo_image_path', models.TextField(blank=True, default=None, null=True)),
                ('horizontal_image_path', models.TextField(blank=True, default=None, null=True)),
                ('vertical_image', models.ImageField(upload_to='media/movie/<django.db.models.fields.CharField>/horizontal')),
                ('circle_image', models.ImageField(blank=True, null=True, upload_to='media/movie/<django.db.models.fields.CharField>/circle')),
                ('big_image_path', models.TextField(blank=True, default=None, null=True)),
                ('actors', models.ManyToManyField(related_name='movie', to='movies.Actor')),
                ('author', models.ManyToManyField(blank=True, related_name='movie', to='movies.Author')),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_degree', to='movies.Degree')),
                ('directors', models.ManyToManyField(related_name='movie', to='movies.Director')),
                ('feature', models.ManyToManyField(related_name='movie', to='movies.Feature')),
                ('genre', models.ManyToManyField(related_name='movie', to='movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='MovieContinue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_be_continue', models.CharField(max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_continue', to='movies.Movie')),
                ('sub_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_continue', to='accounts.SubUser')),
            ],
        ),
    ]
