# Generated by Django 2.2.3 on 2019-07-08 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video_file', models.FileField(upload_to='media/movie/<django.db.models.fields.CharField>/video')),
                ('production', models.DateField(default=django.utils.timezone.now)),
                ('uploaded', models.DateField(default=django.utils.timezone.now)),
                ('synopsis', models.TextField()),
                ('running_time', models.CharField(max_length=10)),
                ('view_count', models.PositiveIntegerField(blank=True)),
                ('logo', models.ImageField(upload_to='media/movie/<django.db.models.fields.CharField>/logo')),
                ('horizontal_photo', models.ImageField(upload_to='media/movie/<django.db.models.fields.CharField>/horizontal')),
                ('vertical_photo', models.ImageField(upload_to='media/movie/<django.db.models.fields.CharField>/horizontal')),
                ('actors', models.ManyToManyField(related_name='movie_actors', to='movies.Actor')),
                ('author', models.ManyToManyField(related_name='movie_author', to='movies.Author')),
                ('degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_degree', to='movies.Degree')),
                ('directors', models.ManyToManyField(related_name='movie_directors', to='movies.Director')),
                ('feature', models.ManyToManyField(related_name='movie_feature', to='movies.Feature')),
                ('genre', models.ManyToManyField(related_name='movie_genre', to='movies.Genre')),
            ],
        ),
    ]
