# Generated by Django 2.2.3 on 2019-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='big_image_path',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='horizontal_image_path',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='logo_image_path',
            field=models.TextField(default=None),
        ),
    ]
