# Generated by Django 2.2.3 on 2019-07-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='circle_photo',
            field=models.ImageField(default=' ', upload_to='media/movie/<django.db.models.fields.CharField>/circle'),
            preserve_default=False,
        ),
    ]
