# Generated by Django 2.2.3 on 2019-07-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.ManyToManyField(related_name='movie_author', to='movies.Author'),
        ),
    ]
