# Generated by Django 2.2.3 on 2019-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_vertical_sample_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='degree_path',
            field=models.TextField(blank=True),
        ),
    ]
