# Generated by Django 2.2.3 on 2019-07-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_circle_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
