# Generated by Django 2.2.3 on 2019-07-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190715_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='big_image_path',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='horizontal_image_path',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='logo_image_path',
            field=models.TextField(default=None, null=True),
        ),
    ]
