# Generated by Django 2.2.3 on 2019-07-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190722_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vertical_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/movie/<django.db.models.fields.CharField>/horizontal'),
        ),
    ]
