# Generated by Django 2.2.3 on 2019-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190709_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sample_video_file',
            field=models.FileField(default=' ', upload_to='media/movie/<django.db.models.fields.CharField>/sample_video'),
            preserve_default=False,
        ),
    ]
