# Generated by Django 2.2.3 on 2019-07-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190724_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='degree_path',
        ),
        migrations.AddField(
            model_name='movie',
            name='degree_path',
            field=models.TextField(blank=True),
        ),
    ]
