# Generated by Django 2.2.3 on 2019-07-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190722_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vertical_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
