# Generated by Django 2.2.3 on 2019-07-05 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190705_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movie_genre', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='parent_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_genre', to='movies.Genre'),
        ),
    ]
