# Generated by Django 2.2.3 on 2019-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190715_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='big_image_path',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='horizontal_image_path',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='logo_image_path',
            field=models.TextField(blank=True, default=None),
        ),
    ]
