# Generated by Django 2.2.3 on 2019-07-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_sample_video_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='production',
            new_name='production_date',
        ),
    ]
