# Generated by Django 2.2.3 on 2019-07-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190705_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='parent_genre',
        ),
    ]
