# Generated by Django 2.2.3 on 2019-07-09 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190709_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='uploaded',
            new_name='uploaded_date',
        ),
    ]
