# Generated by Django 2.2.3 on 2019-07-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190715_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='circle_image',
            field=models.ImageField(blank=True, upload_to='media/movie/<django.db.models.fields.CharField>/circle'),
        ),
    ]
