# Generated by Django 2.2.3 on 2019-07-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_movie_degree_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='degree_path',
            field=models.TextField(blank=True),
        ),
    ]
