# Generated by Django 2.2.3 on 2019-07-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190715_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='big_image_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='circle_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/movie/<django.db.models.fields.CharField>/circle'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='horizontal_image_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='logo_image_path',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sample_video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/movie/<django.db.models.fields.CharField>/sample_video'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='media/movie/<django.db.models.fields.CharField>/video'),
        ),
    ]
