# Generated by Django 2.2.3 on 2019-07-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190709_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='circle_photo',
            new_name='circle_image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='horizontal_photo',
            new_name='horizontal_image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='logo',
            new_name='logo_image',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='vertical_photo',
            new_name='vertical_image',
        ),
    ]
