# Generated by Django 2.2.3 on 2019-07-05 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_genre_parent_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie',
            new_name='video_file',
        ),
    ]
