# Generated by Django 2.2.3 on 2019-07-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190715_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='movie', to='movies.Author'),
        ),
        migrations.AlterField(
            model_name='moviecontinue',
            name='to_be_continue',
            field=models.CharField(max_length=20),
        ),
    ]
