# Generated by Django 2.2.3 on 2019-07-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_degree_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='degree_path',
        ),
    ]
