# Generated by Django 2.2.3 on 2019-07-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_moviecontinue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='horizontal_image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='movie',
            name='horizontal_image_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='logo_image_path',
            field=models.TextField(default=''),
        ),
    ]
