# Generated by Django 2.2.3 on 2019-07-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190716_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecontinue',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
