# Generated by Django 2.2.3 on 2019-07-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20190724_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
