# Generated by Django 2.2.3 on 2019-07-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20190724_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='vertical_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
