# Generated by Django 2.2.3 on 2019-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190724_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
