# Generated by Django 2.2.3 on 2019-07-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20190725_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecontinue',
            name='to_be_continue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
