# Generated by Django 2.2.3 on 2019-07-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_moviecontinue_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='real_running_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
