# Generated by Django 2.2.3 on 2019-08-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_movie_real_running_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ios_main_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
