# Generated by Django 2.2.3 on 2019-08-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_movie_ios_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='circle_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
