# Generated by Django 2.2.3 on 2019-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_auto_20190803_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='movie',
            name='like_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='sample_video_file',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vertical_sample_video_file',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
