# Generated by Django 2.2.3 on 2019-08-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20190805_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_vertical_image_path',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
